### kears 交互式操作

#### 方式1：纯keras backend

In [1]:
from keras import backend as K

Using TensorFlow backend.


In [3]:
# 写法1
session = K.get_session()
kcons = K.constant(value=[[1, 2], [3, 4]])
dot_res=K.dot(kcons,kcons)
dot_res.eval(session=session)

array([[ 7., 10.],
       [15., 22.]], dtype=float32)

In [4]:
# 写法2
kcons = K.constant(value=[[1, 2], [3, 4]])
dot_res=K.dot(kcons,kcons)
K.eval(dot_res)

array([[ 7., 10.],
       [15., 22.]], dtype=float32)

#### 方式2 ：keras backend与tf混用

In [6]:
import tensorflow as tf
from keras import backend as K

In [7]:
# 写法1
sess = tf.Session()
Q_seq=tf.constant([[2.], [1.], [5.]])
sess.run(K.shape(Q_seq))

array([3, 1])

In [10]:
# 写法2
Q_seq=tf.constant([[2.], [1.], [5.]])
res=tf.matmul(tf.transpose(Q_seq),Q_seq) 
K.eval(res)

array([[30.]], dtype=float32)

### API

In [2]:
from keras import initializers

In [8]:
# 变量定义
init_normal=initializers.TruncatedNormal(stddev=0.02)
K.variable(init_normal(shape=[1,2],dtype=K.floatx()),name='w')

<tf.Variable 'w:0' shape=(1, 2) dtype=float32>

In [ ]:
# 

### 自定义层